# This file created by Nullwest LLC - contact hello@nullwest.com
# Git: AI-generated by Claude-3-Sonnet

import os
from dotenv import load_dotenv
import openai

def load_environment():
    load_dotenv()
    openai.api_key = os.getenv('OPENAI_API_KEY')
    return os.getenv('OPENAI_MODEL')

def get_ai_response(prompt, model):
    try:
        response = openai.ChatCompletion.create(
            model=model,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error: {str(e)}"

def main():
    model = load_environment()
    
    while True:
        user_prompt = input("\nEnter your prompt (or 'quit' to exit): ")
        
        if user_prompt.lower() == 'quit':
            break
            
        response = get_ai_response(user_prompt, model)
        print("\nAI Response:")
        print(response)

if __name__ == "__main__":
    main() 